### ISSUE TITLE
Reverse Reveal 

### ISSUE THREAD

**Issue by goonerDroid** [saulmm/Curved-Fab-Reveal-Example#3]
Is there any way to reverse the reveal view?? or how to reverse back to previous state??

**Comment by ferjuarezlp** [comment]
I have the same question, I cannot reverse the state of the widgets or build the inverse animation. Anyway, its a nice animation, great work!

**Comment by goonerDroid** [comment]
i have implemented the reverse reveal will upload the entire code as a new repo and will let you know!

**Comment by saulmm** [comment]
@goonerDroid I suggest you to fork this repository and create a pull request with the new code, I'll review your PR and accept it. :)

**Comment by ferjuarezlp** [comment]
Thanks!! I'll be waiting for that fork :) my solution was very bad and only restart views without any animation

**Comment by garudaonekh** [comment]
Nice animation. Can you give idea on how to reverse it back?

**Comment by sdroider** [comment]
@saulmm Has anyone realized this reverse ???
